### ISSUE TITLE
Error Bootstrapping VPC

### ISSUE THREAD

**Issue by krutisfood** [TechToSpeech/terraform-aws-serverless-static-wordpress#44] opened 2021-07-21 03:34 UTC
Attempting to run `terraform apply` with the example gives the following error
```
│ Error: Invalid count argument
│
│   on vpc_setup/vpc.tf line 92, in resource "aws_route_table_association" "main_subnets_public":
│   92:   count          = length(data.aws_subnet_ids.main_public.ids)
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many
│ instances will be created. To work around this, use the -target argument to first apply only the resources that the count depends
│ on.
╵
╷
│ Error: Invalid count argument
│
│   on vpc_setup/vpc.tf line 101, in resource "aws_route_table_association" "main_subnets_private":
│  101:   count          = length(data.aws_subnet_ids.main_private.ids)
│
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many
│ instances will be created. To work around this, use the -target argument to first apply only the resources that the count depends
│ on.```

**Comment by petewilcock** [comment] 2021-07-21 08:42
Duplicate of https://github.com/TechToSpeech/terraform-aws-serverless-static-wordpress/issues/38 

VPC set-up bundled in the example isn't curated and in the meantime seems to have become incompatible with the latest version of Terraform. I'd suggest setting up your VPC by other means, either manually or using a much better VPC module :)

**Closed by petewilcock** 2021-07-21 08:42 UTC
