### ISSUE TITLE
ECS Task is not able to start due to "standard_init_linux.go:228: exec user process caused: no such file or directory"

### ISSUE THREAD

**Issue by fededalla2** [TechToSpeech/terraform-aws-serverless-static-wordpress#6] opened 2021-06-22 21:03 UTC
I was able to follow all the steps until the [launching-container-customize-wordpress-and-publish-static-site](https://github.com/TechToSpeech/terraform-aws-serverless-static-wordpress#launching-container-customize-wordpress-and-publish-static-site) part where changing the launch value to 1 triggers the task execution which constantly fails.

Every task try to constantly initialize but fails due to the error "standard_init_linux.go:219: exec user process caused: no such file or directory". Example:
![image](https://user-images.githubusercontent.com/9561677/122998409-62669a80-d383-11eb-8ee6-91c90806deed.png)
![image](https://user-images.githubusercontent.com/9561677/122998381-55e24200-d383-11eb-99f6-f8f85b1fe79f.png)

Code build ran successfully and generated the "latest" image, which is the one failing when being run:
[log-events-viewer-result.txt](https://github.com/TechToSpeech/terraform-aws-serverless-static-wordpress/files/6697363/log-events-viewer-result.txt)

I was able to download the image and replicate the issue by running it locally:
![image](https://user-images.githubusercontent.com/9561677/122997944-deacae00-d382-11eb-8201-49d12ab7ff8b.png)

**Comment by petewilcock** [comment] 2021-06-22 21:48
Thanks for this and the level of detail. Everything looks correct and I can't see anything about the build or spec that would cause this - but can I ask - are you running Terraform from Windows?

From what I can see most common cause of this error seems to be CRLF line endings in Windows: https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory

It's _possible_ if you cloned the repo from within Windows, it's mutating the line endings and messing with the entrypoint script just enough to make it break...?

You can probably confirm this by checking your local cache of the module and seeing what the line-endings are:

https://stackoverflow.com/questions/3569997/how-to-find-out-line-endings-in-a-text-file

It feels quite unlikely but it's one possibility.

Can you also try re-triggering the CodeBuild pipeline and building the container again? Just to rule out some kind of strange build-time anomaly.

**Comment by fededalla2** [comment] 2021-06-22 23:56
I'm running it from Windows actually and I had to clone the repo locally due to the RDS password limitation, however I could try again directly from the source module (and just retry until no @ is being used). Have you done the whole execution from a Linux environment?

Re-running the code base success but the problem persists.

**Comment by petewilcock** [comment] 2021-06-23 08:39
This must be the cause - you have probably set your git to check out with windows line endings. This seems to break the docker-entrypoint.sh script and it fails to launch after building. 

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

But I have just released [0.1.2](https://github.com/TechToSpeech/terraform-aws-serverless-static-wordpress/releases/tag/0.1.2) to fix the RDS password issue and updated the docs to reflect your other feedback - so you can use this without cloning now. Let me know if this works for you - you will need to update and re-run the CodeBuild to generate a refresh image.

**Comment by fededalla2** [comment] 2021-06-23 12:14
Tried once more with the remote repository and changing the git new lines handling but still with the same issue. Will try later, probably with a full destroy+apply.

Note: I still had to run docker and codebase manually:

`module.docker_pullpush.null_resource.docker_pullpush: Creating...
module.docker_pullpush.null_resource.docker_pullpush: Provisioning with 'local-exec'...
module.docker_pullpush.null_resource.docker_pullpush (local-exec): Executing: ["cmd" "/C" ".terraform/modules/docker_pullpush/docker_pullpush.sh wordpress:php7.4-apache us-east-2 183218488412 viajesconanto-serverless-wordpress base default"]
module.docker_pullpush.null_resource.docker_pullpush (local-exec): '.terraform' is not recognized as an internal or external command,
module.docker_pullpush.null_resource.docker_pullpush (local-exec): operable program or batch file.
╷
│ Error: local-exec provisioner error
│
│   with module.docker_pullpush.null_resource.docker_pullpush,
│   on .terraform\modules\docker_pullpush\main.tf line 10, in resource "null_resource" "docker_pullpush":
│   10:   provisioner "local-exec" {
│
│ Error running command '.terraform/modules/docker_pullpush/docker_pullpush.sh wordpress:php7.4-apache us-east-2 183218488412 
│ viajesconanto-serverless-wordpress base default': exit status 1. Output: '.terraform' is not recognized as an internal or
│ external command,
│ operable program or batch file.
│
╵`

**Comment by petewilcock** [comment] 2021-06-23 12:32
OK - I think the docker push is again a Windows-specific issue, try updating the definition to: `TechToSpeech/ecr-mirror/aws` version `0.0.7` - I believe it fixes this specific case.

**Comment by Ojaybee** [comment] 2021-06-24 13:05
> This must be the cause - you have probably set your git to check out with windows line endings. This seems to break the docker-entrypoint.sh script and it fails to launch after building.
> 

This worked for me. I checked the cached version of docker-entrypoint.sh (.\modules\codebuild\codebuild_files) and the line endings were Windows.

**Comment by Ojaybee** [comment] 2021-06-24 13:12
> 
> 
> Tried once more with the remote repository and changing the git new lines handling but still with the same issue. Will try later, probably with a full destroy+apply.
> 
> Note: I still had to run docker and codebase manually:
> 
> `module.docker_pullpush.null_resource.docker_pullpush: Creating... module.docker_pullpush.null_resource.docker_pullpush: Provisioning with 'local-exec'... module.docker_pullpush.null_resource.docker_pullpush (local-exec): Executing: ["cmd" "/C" ".terraform/modules/docker_pullpush/docker_pullpush.sh wordpress:php7.4-apache us-east-2 183218488412 viajesconanto-serverless-wordpress base default"] module.docker_pullpush.null_resource.docker_pullpush (local-exec): '.terraform' is not recognized as an internal or external command, module.docker_pullpush.null_resource.docker_pullpush (local-exec): operable program or batch file. ╷ │ Error: local-exec provisioner error │ │ with module.docker_pullpush.null_resource.docker_pullpush, │ on .terraform\modules\docker_pullpush\main.tf line 10, in resource "null_resource" "docker_pullpush": │ 10: provisioner "local-exec" { │ │ Error running command '.terraform/modules/docker_pullpush/docker_pullpush.sh wordpress:php7.4-apache us-east-2 183218488412 │ viajesconanto-serverless-wordpress base default': exit status 1. Output: '.terraform' is not recognized as an internal or │ external command, │ operable program or batch file. │ ╵`

I was having the same problem. Using Docker Desktop make sure WSL2  is set up and you have a Linux distro installed on windows. 
https://andrewlock.net/installing-docker-desktop-for-windows/
Once set up launch the distro and install awscli v2 on it. 
Then follow these steps:
https://github.com/TechToSpeech/terraform-aws-serverless-static-wordpress/issues/9#issuecomment-867054561
I included full access to CodeBuild permissions for the created user as well.

**Comment by chathamdl** [comment] 2021-06-24 18:22
I had the same issue on server 2019, trying the 0.0.7 now.  thanks

**Comment by chathamdl** [comment] 2021-06-24 18:33
Looks like 0.0.7 did not resolve this for me.  Getting CannotPullContainerError: inspect image has been retried 1 time(s): failed to resolve ref "090879126685.dkr.ecr.us-east-1.amazonaws.com/tectalk-serverless-wordpress:latest":

![image](https://user-images.githubusercontent.com/22111072/123314803-045bc380-d4f9-11eb-9194-20eb887c767f.png)

**Comment by petewilcock** [comment] 2021-06-24 18:51
In your case @chathamdl - did you run the CodeBuild job? This must be run at least one to populate the customised container to your ECR repository.

**Comment by fededalla2** [comment] 2021-06-24 22:14
I was able to run everything by referencing the remote terraform modules, I had to instal WSL version 2 with an AWS CLI 2 also, ran successful but when trigerring the ECS Task still fails with the same error message. I tried twice, deleting all ECS Images and Builds just in case but without any luck.

**Comment by fededalla2** [comment] 2021-06-24 23:44
Finally I was able to get it working by manually downloading the wordpress_docker.zip file, changing each of the files to UNIX EOL. Then build locally in my machine, push to remote the latest tag and deploy the ECS Task.

**Comment by chathamdl** [comment] 2021-06-25 01:08
So the codebuild job fails for me saying no image exists. 

![image](https://user-images.githubusercontent.com/22111072/123353780-494f1c80-d530-11eb-9250-d91678a5192b.png)

**Comment by petewilcock** [comment] 2021-06-25 01:54
@chathamdl You are mixing your issue here. You have not pushed the base image to ECR. Check readme for instructions.

**Comment by petewilcock** [comment] 2021-06-25 01:57
> Finally I was able to get it working by manually downloading the wordpress_docker.zip file, changing each of the files to UNIX EOL. Then build locally in my machine, push to remote the latest tag and deploy the ECS Task.

This is a very unique issue not so far seen by other Windows users. I'll do further investigation on how the module could install with CLRF line endings. They are all LF in the repo source.

**Comment by chathamdl** [comment] 2021-06-25 02:20
pete will do, just look like the same thing.  apologies.

**Comment by fededalla2** [comment] 2021-06-25 02:41
Everything works well after the workaround above mentioned, except for the WP2Static plugin, for sure a different issue:
![image](https://user-images.githubusercontent.com/9561677/123361497-8a9df700-d545-11eb-9658-4024c62dbcfd.png)

**Comment by petewilcock** [comment] 2021-06-25 07:04
OK @fededalla2, almost there. Now we're down to wp2static quirks. Best thing to do now is check cloudwatch log groups for ECS and report on the php fatal error there.

**Comment by petewilcock** [comment] 2021-06-25 15:48
Aha, now - this is some kind of weird DNS lag I've seen a few times. The solution seems to be to just.... wait a few minutes and try again, and the DNS resolves and it'll work. Not sure if this is an issue with the Guzzle library or what but it's quite perplexing. 

For plugin-specific issues I'd check their [issue page](https://github.com/leonstafford/wp2static/issues) and raise anything that looks new :)

**Comment by Ojaybee** [comment] 2021-06-25 15:49
Looks good to me!
![image](https://user-images.githubusercontent.com/6020098/123450990-304c7700-d5d5-11eb-9d44-fd915dcb69f9.png)

**Comment by fededalla2** [comment] 2021-06-25 17:01
Just for the record, I finally was getting permission denied due to missing ACL credentials. I went to the plugin option and put ACL as private and the publishing worked.

**Comment by leonstafford** [comment] 2021-06-25 17:19
Please feel free to load up WP2Static or the S3 addon's repos with any relevant issues.

**Comment by petewilcock** [comment] 2021-06-25 17:22
> Just for the record, I finally was getting permission denied due to missing ACL credentials. I went to the plugin option and put ACL as private and the publishing worked.

For the publish step? This is possible actually, the bucket permissions are locked down so I should probably pre-configure the S3 add-on to set the ACL as private always. If you're good now @fededalla2 I'll close this :)

**Comment by fededalla2** [comment] 2021-06-25 17:24
I'm good, we can close it. The work being done in this project is amazing and I really like it. I will some day try to fix these Windows-specific issues from a fresh installation and propose those changes.

**Closed** 2021-06-25 17:25 UTC
Labels: Windows, good first issue

**Comment by CarterSheehan** [comment] 2021-07-04 17:05
> > Finally I was able to get it working by manually downloading the wordpress_docker.zip file, changing each of the files to UNIX EOL. Then build locally in my machine, push to remote the latest tag and deploy the ECS Task.
> 
> This is a very unique issue not so far seen by other Windows users. I'll do further investigation on how the module could install with CLRF line endings. They are all LF in the repo source.

I am experiencing the same issue; I am on Windows 10 and when I check the line endings of the files inside wordpress_docker.zip in my cached terraform files, they are all in Windows line endings.
