### ISSUE TITLE
Error: Invalid count argument

### ISSUE THREAD

**Issue by galacoder** [TechToSpeech/terraform-aws-serverless-static-wordpress#52] opened 2022-04-05 04:30 UTC
Hi there, 

First of all, I want to thank you for creating such a great approach to serverless static wordpress. I can't wait to try it out. However, I got an error.

I tried to use your script with ->  "terreform init" and it worked. However, when I tried to "terraform apply" I got an error. I am a newbie with Terreform and I don't know how to fix it. Please check the attachment and advise!

![Screen Shot 2022-04-05 at 11 27 52](https://user-images.githubusercontent.com/13715145/161678848-a6448b2e-a54e-4f80-9e74-197530bc2cc1.png)

![Screen Shot 2022-04-05 at 11 25 58](https://user-images.githubusercontent.com/13715145/161678774-d275b5ae-e611-49b9-8c1d-68b7030400c2.png)

Mysetup zipfile: 
[wordpress-serverless-stati.zip](https://github.com/TechToSpeech/terraform-aws-serverless-static-wordpress/files/8414957/wordpress-serverless-stati.zip)

I am looking forward to hearing from you soon. 
Best Regards, 
Sang.

**Comment by petewilcock** [comment] 2022-04-05 07:57
Ah my VPC example module strikes again! The VPC set-up is not part of the module and is just as an example only - the problem is that it no longer works properly and it needs to update it - but you could also just use an existing VPC or one created manually by inserting the correct identifiers. 

Having said that, you can probably workaround this error by running the first targetted command first:

```
terraform apply -target module.peterdotcloud_website.vpc_setup.aws_subnet.main_public -target module.peterdotcloud_website.vpc_setup.aws_subnet.main_private 
```
and then do a regular `terraform apply`, and it should work. 

I really must remove the VPC example or update it :)

**Comment by galacoder** [comment] 2022-04-05 14:13
Thanks for your quick response. Please don't remove it. Update it instead. I couldn't make it work. Check the attachment. 

I really love to try it out as I am developing low-cost eLearning and web apps using WordPress for my college in Vietnam. 

Your help is very much appreciated,
Sang. 
<img width="1013" alt="Screen Shot 2022-04-05 at 21 08 42" src="https://user-images.githubusercontent.com/13715145/161773710-3a56749f-7a63-4906-a754-6ca81a2faa0b.png">
ed.

**Comment by petewilcock** [comment] 2022-04-05 14:32
Apologies, trying to guess your exact set-up, try this:

`erraform apply -target module.peterdotcloud_website.module.vpc_setup.aws_subnet.main_public -target module.peterdotcloud_website.module.vpc_setup.aws_subnet.main_private`

**Comment by petewilcock** [comment] 2022-04-05 20:47
@galacoder I've just realised that @krutisfood had very kindly prepped a PR with some fixes for the VPC example module. I've merged these directly into the main branch and it will also be available in the upcoming 0.2.0 release of the module.

**Comment by galacoder** [comment] 2022-04-05 23:25
Thank @petewilcock for your timely response. I did replace my vpc example module with your new merged files. Somehow, I hit another problem tho. Please check the log :(

I was wondering maybe cuz I didn't input the main.tf file correctly? As I am a newbie with Terraform and AWS, I didn't really know which I should change or keep. By the way, as I am staying in Vietnam, can I switch the provider to Singapore region (ap-southeast-1) ?

If you got the chance, It would be great if u could provide in the example which info I can keep and which one I ave to replace. 

Please advise! 

`
Plan: 103 to add, 0 to change, 0 to destroy.
‚ï∑
‚îÇ Warning: Argument is deprecated
‚îÇ
‚îÇ   with module.peterdotcloud_website.module.cloudfront.aws_s3_bucket.wordpress_bucket,
‚îÇ   on .terraform/modules/peterdotcloud_website/modules/cloudfront/distribution.tf line 4, in resource "aws_s3_bucket" "wor
dpress_bucket":
‚îÇ    4: resource "aws_s3_bucket" "wordpress_bucket" {
‚îÇ
‚îÇ Use the aws_s3_bucket_server_side_encryption_configuration resource instead
‚îÇ
‚îÇ (and 5 more similar warnings elsewhere)
‚ïµ

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.peterdotcloud_website.random_id.rds_snapshot: Creating...
module.peterdotcloud_website.random_password.serverless_wordpress_password: Creating...
module.peterdotcloud_website.random_password.serverless_wordpress_password: Creation complete after 0s [id=none]
module.peterdotcloud_website.random_id.rds_snapshot: Creation complete after 0s [id=CzrgNqHpqug]
module.peterdotcloud_website.module.codebuild.local_file.php_ini: Creating...
module.peterdotcloud_website.module.codebuild.local_file.php_ini: Creation complete after 0s [id=076454b250ffae9107d34a3b3e
61f3eb9644921e]
module.peterdotcloud_website.module.codebuild.data.archive_file.code_build_package: Reading...
module.peterdotcloud_website.module.codebuild.data.archive_file.code_build_package: Read complete after 1s [id=8f789d38d8ce
5a9eccebd06a7a297f80465ab9c7]
module.peterdotcloud_website.aws_acm_certificate.wordpress_site: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_rule.ecs_wordpress_service_deployment_state: Creat
ing...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_rule.rds_wordpress_cluster_state: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_log_group.lambda_slack: Creating...
module.peterdotcloud_website.aws_cloudwatch_log_group.wordpress_container: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_iam_role.lambda: Creating...
module.peterdotcloud_website.aws_cloudwatch_log_group.serverless_wordpress: Creating...
module.peterdotcloud_website.module.codebuild.aws_security_group.codebuild_security_group: Creating...
module.peterdotcloud_website.module.codebuild.aws_s3_bucket.code_source: Creating...
module.peterdotcloud_website.module.waf[0].aws_wafv2_web_acl.default: Creating...
module.peterdotcloud_website.aws_security_group.aurora_serverless_group: Creating...
module.peterdotcloud_website.aws_db_subnet_group.main_vpc: Creating...
module.peterdotcloud_website.aws_acm_certificate.wordpress_site: Creation complete after 8s [id=arn:aws:acm:us-east-1:41415
9720817:certificate/96d682d1-55ae-4046-8073-cde5176354a8]
module.peterdotcloud_website.aws_iam_role.wordpress_task: Creating...
module.peterdotcloud_website.module.waf[0].aws_wafv2_web_acl.default: Creation complete after 8s [id=bf9379e9-3732-4e45-baa
b-a435bea2b512]
aws_route53_zone.apex: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_log_group.lambda_slack: Creation complete after 10s [id=
/aws/lambda/wptest_lambda_slack]
module.peterdotcloud_website.aws_cloudwatch_log_group.wordpress_container: Creation complete after 10s [id=/aws/ecs/wptest-
serverless-wordpress-container]
module.peterdotcloud_website.aws_cloudwatch_log_group.serverless_wordpress: Creation complete after 10s [id=/aws/rds/cluste
r/wptest-serverless-wordpress/error]
module.peterdotcloud_website.aws_route53_record.www: Creating...
module.peterdotcloud_website.aws_efs_file_system.wordpress_persistent: Creating...
module.peterdotcloud_website.aws_security_group.efs_security_group: Creating...
module.peterdotcloud_website.aws_ecs_cluster.wordpress_cluster: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_rule.rds_wordpress_cluster_state: Still creating..
. [10s elapsed]
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_rule.ecs_wordpress_service_deployment_state: Still
 creating... [10s elapsed]
module.peterdotcloud_website.module.lambda_slack[0].aws_iam_role.lambda: Still creating... [10s elapsed]
module.peterdotcloud_website.module.codebuild.aws_s3_bucket.code_source: Still creating... [10s elapsed]
module.peterdotcloud_website.module.lambda_slack[0].aws_iam_role.lambda: Creation complete after 11s [id=wptest-lambda-serv
ice-role]
module.peterdotcloud_website.module.codebuild.aws_iam_role.codebuild_service_role: Creating...
module.peterdotcloud_website.module.codebuild.aws_cloudwatch_log_group.wordpress_docker_build: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_rule.ecs_wordpress_service_deployment_state: Creat
ion complete after 13s [id=wptest-ecs-wordpress-deployment-state]
module.peterdotcloud_website.aws_security_group.wordpress_security_group: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_rule.rds_wordpress_cluster_state: Creation complet
e after 13s [id=wptest-rds-wordpress-cluster-state]
module.peterdotcloud_vpc.aws_vpc.main: Creating...
module.peterdotcloud_website.aws_iam_role.wordpress_task: Creation complete after 6s [id=wptest_WordpressTaskRole]
module.peterdotcloud_website.aws_ecr_repository.serverless_wordpress: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_lambda_function.lambda_slack: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_iam_role_policy.lambda-cloudwatch-logs: Creating...
module.peterdotcloud_website.module.codebuild.aws_cloudwatch_log_group.wordpress_docker_build: Creation complete after 5s [id=/aws/codebuild/wp
test-serverless-wordpress-docker-build]
module.peterdotcloud_website.module.lambda_slack[0].aws_iam_role_policy_attachment.lambda_basic: Creating...
module.peterdotcloud_website.module.codebuild.aws_iam_role.codebuild_service_role: Creation complete after 5s [id=wptest_CodeBuildServiceRole]
module.peterdotcloud_website.aws_iam_role_policy_attachment.wordpress_role_attachment_ecs: Creating...
module.peterdotcloud_website.aws_ecr_repository.serverless_wordpress: Creation complete after 4s [id=wptest-serverless-wordpress]
module.peterdotcloud_website.aws_iam_role_policy_attachment.wordpress_role_attachment_cloudwatch: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_iam_role_policy_attachment.lambda_basic: Creation complete after 2s [id=wptest-lambda-s
ervice-role-20220405231647965600000003]
module.peterdotcloud_website.module.lambda_slack[0].aws_iam_role_policy.lambda-cloudwatch-logs: Creation complete after 2s [id=wptest-lambda-se
rvice-role:wptest-lambda-cloudwatch-logs]
module.peterdotcloud_website.aws_route53_record.wordpress_acm_validation["dev.sangletech.com"]: Creating...
module.peterdotcloud_website.aws_route53_record.wordpress_acm_validation["www.dev.sangletech.com"]: Creating...
module.peterdotcloud_website.aws_iam_role_policy_attachment.wordpress_role_attachment_ecs: Creation complete after 3s [id=wptest_WordpressTaskR
ole-20220405231648728600000004]
module.peterdotcloud_website.module.codebuild.aws_iam_role_policy_attachment.codebuild_role_attachment: Creating...
aws_route53_zone.apex: Still creating... [10s elapsed]
module.peterdotcloud_website.aws_efs_file_system.wordpress_persistent: Still creating... [10s elapsed]
module.peterdotcloud_website.aws_ecs_cluster.wordpress_cluster: Still creating... [10s elapsed]
module.peterdotcloud_website.aws_iam_role_policy_attachment.wordpress_role_attachment_cloudwatch: Creation complete after 2s [id=wptest_Wordpre
ssTaskRole-20220405231650064300000005]
module.peterdotcloud_website.module.codebuild.aws_s3_bucket.code_source: Still creating... [20s elapsed]
module.peterdotcloud_website.aws_efs_file_system.wordpress_persistent: Creation complete after 11s [id=fs-05a6499a716616272]
module.peterdotcloud_website.aws_efs_access_point.wordpress_efs: Creating...
module.peterdotcloud_website.module.codebuild.aws_iam_role_policy_attachment.codebuild_role_attachment: Creation complete after 3s [id=wptest_C
odeBuildServiceRole-20220405231651341000000006]
module.peterdotcloud_website.aws_ecs_cluster.wordpress_cluster: Creation complete after 13s [id=arn:aws:ecs:eu-west-1:414159720817:cluster/wpte
st_wordpress]
module.peterdotcloud_vpc.aws_vpc.main: Still creating... [10s elapsed]
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_rule.ecs_wordpress_instance_state: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_rule.ecs_wordpress_task_state: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_lambda_function.lambda_slack: Still creating... [10s elapsed]
module.peterdotcloud_website.aws_efs_access_point.wordpress_efs: Creation complete after 4s [id=fsap-07176b2caffcbc70c]
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_rule.ecs_wordpress_task_state: Creation complete after 3s [id=wptest-e
cs-wordpress-task-state]
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_rule.ecs_wordpress_instance_state: Creation complete after 3s [id=wpte
st-ecs-wordpress-instance-state]
module.peterdotcloud_website.module.codebuild.aws_s3_bucket.code_source: Creation complete after 26s [id=wptest-build]
module.peterdotcloud_website.module.codebuild.aws_s3_bucket_public_access_block.code_source: Creating...
module.peterdotcloud_website.module.codebuild.aws_s3_bucket_object.wordpress_dockerbuild: Creating...
module.peterdotcloud_website.module.codebuild.aws_s3_bucket_public_access_block.code_source: Creation complete after 3s [id=wptest-build]
aws_route53_zone.apex: Still creating... [20s elapsed]
module.peterdotcloud_website.module.lambda_slack[0].aws_lambda_function.lambda_slack: Creation complete after 16s [id=wptest_lambda_slack]
module.peterdotcloud_website.module.lambda_slack[0].aws_lambda_permission.allow_rule_task_state: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_lambda_permission.allow_rule_instance_state: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_lambda_permission.allow_rule_cluster_state: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_target.lambda_slack_deployment_state: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_lambda_permission.allow_rule_deployment_state: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_target.lambda_slack_instance_state: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_target.lambda_slack_cluster_state: Creating...
module.peterdotcloud_vpc.aws_vpc.main: Still creating... [20s elapsed]
module.peterdotcloud_website.module.lambda_slack[0].aws_lambda_permission.allow_rule_task_state: Creation complete after 2s [id=AllowExecutionF
romECSTaskState]
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_target.lambda_slack_deployment_state: Creation complete after 2s [id=w
ptest-ecs-wordpress-deployment-state-terraform-20220405231702484400000007]
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_target.lambda_slack_instance_state: Creation complete after 2s [id=wpt
est-ecs-wordpress-instance-state-terraform-20220405231702484400000008]
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_target.lambda_slack_cluster_state: Creation complete after 2s [id=wpte
st-rds-wordpress-cluster-state-terraform-20220405231702484800000009]
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_target.lambda_slack_task_state: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_lambda_permission.allow_rule_instance_state: Creation complete after 4s [id=AllowExecut
ionFromECSInstanceState]
module.peterdotcloud_website.module.codebuild.aws_s3_bucket_object.wordpress_dockerbuild: Still creating... [10s elapsed]
module.peterdotcloud_website.module.lambda_slack[0].aws_lambda_permission.allow_rule_cluster_state: Creation complete after 6s [id=AllowExecuti
onFromRDSClusterState]
module.peterdotcloud_website.module.lambda_slack[0].aws_lambda_permission.allow_rule_deployment_state: Creation complete after 8s [id=AllowExec
utionFromECSDeploymentState]
aws_route53_zone.apex: Still creating... [30s elapsed]
module.peterdotcloud_website.module.codebuild.aws_s3_bucket_object.wordpress_dockerbuild: Creation complete after 14s [id=wordpress_docker.zip]
module.peterdotcloud_website.module.codebuild.aws_codebuild_project.wordpress_docker_build: Creating...
module.peterdotcloud_website.module.lambda_slack[0].aws_cloudwatch_event_target.lambda_slack_task_state: Creation complete after 8s [id=wptest-
ecs-wordpress-task-state-terraform-2022040523170445640000000a]
module.peterdotcloud_website.module.codebuild.aws_codebuild_project.wordpress_docker_build: Creation complete after 2s [id=arn:aws:codebuild:eu
-west-1:414159720817:project/wptest-serverless-wordpress-docker-build]
module.peterdotcloud_vpc.aws_vpc.main: Still creating... [30s elapsed]
module.peterdotcloud_vpc.aws_vpc.main: Creation complete after 33s [id=vpc-072d95bd21b8c242d]
module.peterdotcloud_vpc.data.aws_subnet_ids.main_private: Reading...
module.peterdotcloud_vpc.data.aws_subnet_ids.main_public: Reading...
module.peterdotcloud_vpc.aws_internet_gateway.main: Creating...
module.peterdotcloud_vpc.aws_route_table.main_public: Creating...
module.peterdotcloud_vpc.aws_subnet.main_private[0]: Creating...
module.peterdotcloud_vpc.aws_subnet.main_public[0]: Creating...
module.peterdotcloud_vpc.aws_subnet.main_public[1]: Creating...
module.peterdotcloud_vpc.aws_vpc_endpoint.main_s3: Creating...
module.peterdotcloud_vpc.aws_subnet.main_private[2]: Creating...
module.peterdotcloud_vpc.aws_route_table.main_private: Creating...
module.peterdotcloud_vpc.aws_subnet.main_private[1]: Creating...
aws_route53_zone.apex: Still creating... [40s elapsed]
module.peterdotcloud_vpc.aws_route_table.main_public: Creation complete after 4s [id=rtb-01ac199ff9d2294e1]
module.peterdotcloud_vpc.aws_subnet.main_public[2]: Creating...
module.peterdotcloud_vpc.aws_subnet.main_private[2]: Creation complete after 4s [id=subnet-0ddef58cda3b4ee2d]
module.peterdotcloud_vpc.aws_subnet.main_private[0]: Creation complete after 4s [id=subnet-03d76b7452a4eb976]
module.peterdotcloud_vpc.aws_internet_gateway.main: Creation complete after 5s [id=igw-0ef59277879833ec6]
module.peterdotcloud_vpc.aws_route_table.main_private: Creation complete after 4s [id=rtb-06a14be7cacac0d73]
module.peterdotcloud_vpc.aws_subnet.main_private[1]: Creation complete after 4s [id=subnet-0685e014ad35b6608]
module.peterdotcloud_vpc.aws_route.public_out_to_internet: Creating...
module.peterdotcloud_vpc.data.aws_subnet_ids.main_public: Still reading... [10s elapsed]
module.peterdotcloud_vpc.data.aws_subnet_ids.main_private: Still reading... [10s elapsed]
module.peterdotcloud_vpc.aws_vpc_endpoint.main_s3: Still creating... [10s elapsed]
module.peterdotcloud_vpc.aws_subnet.main_public[1]: Still creating... [10s elapsed]
module.peterdotcloud_vpc.aws_subnet.main_public[0]: Still creating... [10s elapsed]
module.peterdotcloud_vpc.aws_route.public_out_to_internet: Creation complete after 5s [id=r-rtb-01ac199ff9d2294e11080289494
module.peterdotcloud_vpc.aws_vpc_endpoint.main_s3: Creation complete after 11s [id=vpce-05b5818a22740150a]
module.peterdotcloud_vpc.aws_vpc_endpoint_route_table_association.main_s3_public: Creating...
module.peterdotcloud_vpc.aws_vpc_endpoint_route_table_association.main_s3_private: Creating...
aws_route53_zone.apex: Still creating... [50s elapsed]
module.peterdotcloud_vpc.aws_subnet.main_public[2]: Still creating... [10s elapsed]
module.peterdotcloud_vpc.aws_vpc_endpoint_route_table_association.main_s3_public: Creation complete after 5s [id=a-vpce-05b
5818a22740150a3019466664]
module.peterdotcloud_vpc.aws_vpc_endpoint_route_table_association.main_s3_private: Creation complete after 5s [id=a-vpce-05
b5818a22740150a226250553]
module.peterdotcloud_vpc.aws_subnet.main_public[1]: Creation complete after 16s [id=subnet-0a36a9701b7d8f352]
module.peterdotcloud_vpc.aws_subnet.main_public[0]: Creation complete after 16s [id=subnet-081831a347e247de9]
aws_route53_zone.apex: Creation complete after 56s [id=Z0963119XVGSNCP2ROK5]
null_resource.update_nameservers: Creating...
null_resource.update_nameservers: Provisioning with 'local-exec'...
null_resource.update_nameservers (local-exec): Executing: ["/bin/sh" "-c" "aws route53domains update-domain-nameservers --region ap-southeast-1
 --domain-name dev.sangletech.com --nameservers Name=ns-1202.awsdns-22.org Name=ns-1852.awsdns-39.co.uk Name=ns-218.awsdns-27.com Name=ns-985.a
wsdns-59.net --profile devsangletech"]
module.peterdotcloud_vpc.data.aws_subnet_ids.main_private: Still reading... [20s elapsed]
module.peterdotcloud_vpc.data.aws_subnet_ids.main_public: Still reading... [20s elapsed]
module.peterdotcloud_vpc.aws_subnet.main_public[2]: Creation complete after 16s [id=subnet-0c13efa65df6c4f2a]

null_resource.update_nameservers (local-exec): The config profile (devsangletech) could not be found
‚ï∑
‚îÇ Warning: Argument is deprecated
‚îÇ
‚îÇ   with module.peterdotcloud_website.module.codebuild.aws_s3_bucket.code_source,
‚îÇ   on .terraform/modules/peterdotcloud_website/modules/codebuild/main.tf line 6, in resource "aws_s3_bucket" "code_source":
‚îÇ    6: resource "aws_s3_bucket" "code_source" {
‚îÇ
‚îÇ Use the aws_s3_bucket_server_side_encryption_configuration resource instead
‚îÇ
‚îÇ (and one more similar warning elsewhere)
‚ïµ
‚ï∑
‚îÇ Error: local-exec provisioner error
‚îÇ
‚îÇ   with null_resource.update_nameservers,
‚îÇ   on main.tf line 82, in resource "null_resource" "update_nameservers":
‚îÇ   82:   provisioner "local-exec" {
‚îÇ
‚îÇ Error running command 'aws route53domains update-domain-nameservers --region ap-southeast-1 --domain-name dev.sangletech.com --nameservers
‚îÇ Name=ns-1202.awsdns-22.org Name=ns-1852.awsdns-39.co.uk Name=ns-218.awsdns-27.com Name=ns-985.awsdns-59.net --profile devsangletech': exit
‚îÇ status 255. Output:
‚îÇ The config profile (devsangletech) could not be found
‚îÇ
‚ïµ
‚ï∑
‚îÇ Error: no matching EC2 Subnets found
‚îÇ
‚îÇ   with module.peterdotcloud_vpc.data.aws_subnet_ids.main_public,
‚îÇ   on vpc_setup/vpc.tf line 21, in data "aws_subnet_ids" "main_public":
‚îÇ   21: data "aws_subnet_ids" "main_public" {
‚îÇ
‚ïµ
‚ï∑
‚îÇ Error: no matching EC2 Subnets found
‚îÇ
‚îÇ   with module.peterdotcloud_vpc.data.aws_subnet_ids.main_private,
‚îÇ   on vpc_setup/vpc.tf line 28, in data "aws_subnet_ids" "main_private":
‚îÇ   28: data "aws_subnet_ids" "main_private" {
‚îÇ
‚ïµ
‚ï∑
‚îÇ Error: NoSuchHostedZone: No hosted zone found with ID: Z00437553UWAVIRHANGCN
‚îÇ       status code: 404, request id: 15c73f41-c624-4327-8acd-6b5ce31f6391
‚îÇ
‚îÇ   with module.peterdotcloud_website.aws_route53_record.wordpress_acm_validation["dev.sangletech.com"],
‚îÇ   on .terraform/modules/peterdotcloud_website/acm.tf line 13, in resource "aws_route53_record" "wordpress_acm_validation":
‚îÇ   13: resource "aws_route53_record" "wordpress_acm_validation" {
‚îÇ
‚ïµ
‚ï∑
‚îÇ Error: NoSuchHostedZone: No hosted zone found with ID: Z00437553UWAVIRHANGCN
‚îÇ       status code: 404, request id: f0d751f9-ce21-4622-9b33-0c36f16a120f
‚îÇ
‚îÇ   with module.peterdotcloud_website.aws_route53_record.wordpress_acm_validation["www.dev.sangletech.com"],
‚îÇ   on .terraform/modules/peterdotcloud_website/acm.tf line 13, in resource "aws_route53_record" "wordpress_acm_validation":
‚îÇ   13: resource "aws_route53_record" "wordpress_acm_validation" {
‚îÇ
‚ïµ
‚ï∑
‚îÇ Error: error creating Security Group (wptest_efs_sg): InvalidVpcID.NotFound: The vpc ID 'vpc-e121c09b' does not exist
‚îÇ       status code: 400, request id: 3bb7c8c5-26f9-4c03-869d-16af00efc5ed
‚îÇ
‚îÇ   with module.peterdotcloud_website.aws_security_group.efs_security_group,
‚îÇ   on .terraform/modules/peterdotcloud_website/ecs.tf line 75, in resource "aws_security_group" "efs_security_group":
‚îÇ   75: resource "aws_security_group" "efs_security_group" {
‚îÇ
‚ïµ
‚ï∑
‚îÇ Error: error creating Security Group (wptest_wordpress_sg): InvalidVpcID.NotFound: The vpc ID 'vpc-e121c09b' does not exist
‚îÇ       status code: 400, request id: 735535b7-d8f0-46bf-8795-6d1bb9bb19d5
‚îÇ
‚îÇ   with module.peterdotcloud_website.aws_security_group.wordpress_security_group,
‚îÇ   on .terraform/modules/peterdotcloud_website/ecs.tf line 153, in resource "aws_security_group" "wordpress_security_group":
‚îÇ  153: resource "aws_security_group" "wordpress_security_group" {
‚îÇ
‚ïµ
‚ï∑
‚îÇ Error: NoSuchHostedZone: No hosted zone found with ID: Z00437553UWAVIRHANGCN
‚îÇ       status code: 404, request id: 46672afb-9b9b-47d6-8be5-acdd5cc67d8b
‚îÇ
‚îÇ   with module.peterdotcloud_website.aws_route53_record.www,
‚îÇ   on .terraform/modules/peterdotcloud_website/r53.tf line 1, in resource "aws_route53_record" "www":
‚îÇ    1: resource "aws_route53_record" "www" {
‚îÇ
‚ïµ
‚ï∑
‚îÇ Error: error creating Security Group (dev.sangletech.com_aurora_mysql_sg): InvalidVpcID.NotFound: The vpc ID 'vpc-e121c09b' does not exist
‚îÇ       status code: 400, request id: ddd5b83a-8ec1-4e18-966d-2614ae27cbf1
‚îÇ
‚îÇ   with module.peterdotcloud_website.aws_security_group.aurora_serverless_group,
‚îÇ   on .terraform/modules/peterdotcloud_website/rds.tf line 7, in resource "aws_security_group" "aurora_serverless_group":
‚îÇ    7: resource "aws_security_group" "aurora_serverless_group" {
‚îÇ
‚ïµ
‚ï∑
‚îÇ Error: Error creating DB Subnet Group: InvalidParameterValue: Some input subnets in :[subnet-04b97235, subnet-04b97734, s
nvalid.
‚îÇ       status code: 400, request id: eb309a4e-5542-4f41-acd4-157b30fd5d1f
‚îÇ
‚îÇ   with module.peterdotcloud_website.aws_db_subnet_group.main_vpc,
‚îÇ   on .terraform/modules/peterdotcloud_website/rds.tf line 23, in resource "aws_db_subnet_group" "main_vpc":
‚îÇ   23: resource "aws_db_subnet_group" "main_vpc" {
‚îÇ
‚ïµ
‚ï∑
‚îÇ Error: error creating Security Group (wptest_codebuild_sg): InvalidVpcID.NotFound: The vpc ID 'vpc-e121c09b' does not exi
‚îÇ       status code: 400, request id: d74c134d-13fd-481a-b664-526e1d186468
‚îÇ
‚îÇ   with module.peterdotcloud_website.module.codebuild.aws_security_group.codebuild_security_group,
‚îÇ   on .terraform/modules/peterdotcloud_website/modules/codebuild/main.tf line 65, in resource "aws_security_group" "codebu
‚îÇ   65: resource "aws_security_group" "codebuild_security_group" {

`

**Comment by petewilcock** [comment] 2022-04-06 07:34
A lot of issues here, one is that you don't have a local credential profile called 'devsangletech' set up.

Double-check you have the provider configuration for UE1 set up as mentioned in the README. 

It can't find the hosted zone ID you've passed in `Z00437553UWAVIRHANGCN` so it can't create any records to validate ACM. 

I would check the console log for each error and see if you can resolve the referencing error it's complaining about, and then attempt to re-plan/apply.

**Closed** 2022-04-22 19:46 UTC
